version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: ${DB_PORT}
        protocol: tcp
        mode: ingress
