@host=http://localhost:3000/v1/posts
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGxvY2FsLmhvc3QiLCJSb2xlSUQiOjQsIlVzZXJJRCI6MSwiVXNlck5hbWUiOiJhZG1pbiIsImV4cCI6MTcwMzAwNTgwNH0.7Nrhir6Lz_QomP05Rl_xiaEUIXlqPu0hyCBzO1ezK2c

###
POST http://localhost:3000/v1/users/login
Content-Type: application/json
Accept: application/json

{
  "Email": "admin@local.host",
  "Password": "admin@123"
}

###

POST {{host}}/
Content-Type: application/json
Authorization: {{token}}

{
  "Title": "My post wit tag!",
  "Body": "<h1>Welcome</h1>",
  "Tags": [
    1, 2, 3, 4
  ]
}

###

GET {{host}}/

###

GET {{host}}/1

###

PUT {{host}}/1
Content-Type: application/json
Authorization: {{token}}

{
  "Title":"I changed this",
  "Body": "JELLO",
  "Tags": [1]
}