@host=http://localhost:3000/v1/posts
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGxvY2FsLmhvc3QiLCJSb2xlSUQiOjQsIlVzZXJJRCI6MSwiVXNlck5hbWUiOiJhZG1pbiIsImV4cCI6MTcwMzI2OTQxN30.fAeDO0iAAa4jdSXZceFiSgpeOhgMF7QXnBCRoYRHExU

###
POST http://localhost:3000/v1/users/login
Content-Type: application/json
Accept: application/json

{
  "Email": "admin@local.host",
  "Password": "admin@123"
}

###

POST {{host}}/
Content-Type: application/json;charset=utf-8
Authorization: {{token}}
Accept: application/json;charset=utf-8

{
  "Title": "My post wit tag!",
  "Body": "<h1>Hello World!</h1>"
}

###

GET {{host}}/

###

GET {{host}}/2

###

PUT {{host}}/2
Content-Type: application/json
Authorization: {{token}}

{
  "Tags": []
}