@host=http://localhost:3000/v1/users


###

POST {{host}}/register
Content-Type: application/json
Accept: application/json

{
  "UserName": "Kunniii",
  "Email": "kunniii@codechovui.dev",
  "Password": "1234@asdf"
}

###

POST {{host}}/login
Content-Type: application/json
Accept: application/json

{
  "Email": "kunniii@codechovui.dev",
  "Password": "1234@asdf"
}

###

POST {{host}}/verify
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGxvY2FsLmhvc3QiLCJSb2xlSUQiOjQsIlVzZXJJRCI6MSwiVXNlck5hbWUiOiJhZG1pbiIsImV4cCI6MTcwMzAwMDYzMH0.xS7xydpsXwARrrK4Qvoeoxes9oF3Tt4-EuhQQIjeWOo
###

POST {{host}}/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGxvY2FsLmhvc3QiLCJSb2xlSUQiOjQsIlVzZXJJRCI6MSwiVXNlck5hbWUiOiJhZG1pbiIsImV4cCI6MTcwMzI0NTc5Mn0.pOXhoOz79KtjqxO5AVXF_gKyNW_x6MEd7nBxIRIRV9k

###

POST {{host}}/login
Content-Type: application/json
Accept: application/json

{
  "Email": "admin@local.host",
  "Password": "admin@123"
}

###